services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    networks:
      - fastapi-net
    environment:
      - OLLAMA_URI=http://ollama:11434
      - QDRANT_URI=http://qdrant:6333
      - DB_HOST=postgres-db-local
      - DB_PORT=5432
    env_file:
      - config/.env

  ollama:
    build:
      context: ./ollama  # Adjusted path
      dockerfile: Dockerfile  # Corrected reference
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/ollama
    networks:
      - fastapi-net
    entrypoint: [ "/bin/bash", "/ollama/pull-llama.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - fastapi-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-db-local:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartCode_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fastapi-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    image: registry.gitlab.com/kdg-ti/the-lab/teams-24-25/gang-of-three-smart-code-analysis/backend:main
    ports:
      - "5000:5000"
    environment:
      AI_SERVICE_URL: "http://web:8000"
    depends_on:
      postgres-db-local:
        condition: service_healthy
    networks:
      - fastapi-net

networks:
  fastapi-net:
    driver: bridge

volumes:
  postgres-data: