services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    networks:
      - fastapi-net
    depends_on:
      ollama:
        condition: service_started
    environment:
      - OLLAMA_URI=http://ollama:11434

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/ollama
    networks:
      - fastapi-net
    entrypoint: [ "/bin/bash", "/ollama/pull-llama.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  fastapi-net:
    driver: bridge
