version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    networks:
      - fastapi-net
    depends_on:
      ollama:
        condition: service_started
    environment:
      - OLLAMA_URI=http://ollama:11434/v1
      - QDRANT_URI=http://qdrant:6333
    env_file:
      - .env # Must contain LOGFIRE_TOKEN

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/ollama
    networks:
      - fastapi-net
    entrypoint: [ "/bin/bash", "/ollama/pull-llama.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - fastapi-net

networks:
  fastapi-net:
    driver: bridge
